---
secretStore:
  name: vault-backend
  kind: ClusterSecretStore

configdemomysecret:
  key: secret/data/global/config-demo

configdemosecret:
  key: secret/data/global/config-demo

global:
  hubClusterDomain: cluster-9l6sz.9l6sz.sandbox5174.opentlc.com
  localClusterDomain: region-one.example.com

clusterGroup:
  isHubCluster: true
