---
apiVersion: "external-secrets.io/v1beta1"
kind: ExternalSecret
metadata:
  name: config-demo-mysecret 
  namespace: config-demo
spec:
  refreshInterval: 15s 
  secretStoreRef: 
    name: {{ .Values.secretStore.name }}
    kind: {{ .Values.secretStore.kind }}
  target:
    name: config-demo-mysecret
    template:
      type: Opaque
  dataFrom: 
  - extract:
      key: {{ .Values.configdemomysecret.key }}
